"use client";

import { Mail, Clock, MessageCircle, Phone, Database, CalendarDays, Check, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import type { OutreachDraft } from "@/types";
import { cn } from "@/lib/utils";

type StepState = "done" | "awaiting" | "rejected" | "planned";

interface TimelineStep {
  id: string;
  label: string;
  detail: string;
  icon: React.ElementType;
  state: StepState;
}

const STATE_BADGE: Record<StepState, { label: string; variant: "success" | "warning" | "danger" | "outline" }> = {
  done: { label: "Completed", variant: "success" },
  awaiting: { label: "Awaiting approval", variant: "warning" },
  rejected: { label: "Rejected", variant: "danger" },
  planned: { label: "Planned integration", variant: "outline" },
};

/**
 * The only step this backend actually implements end-to-end is Email
 * (draft generation + human approve/reject, via /queue/*). Everything
 * after it — best-time prediction, WhatsApp, Twilio calling, CRM
 * write-back, meeting scheduling — has no backend code anywhere in
 * this repo (confirmed: no Twilio dependency, no WhatsApp integration,
 * channel defaults to "email" and is never set otherwise, "Connect CRM"
 * only adds a decorative chip). They're kept visible here because
 * they're on the product roadmap, but always labeled "Planned
 * integration" — never given a fake in-progress or completed state.
 */
export function OutreachTimeline({ draft }: { draft: OutreachDraft }) {
  const emailState: StepState =
    draft.status === "approved" || draft.status === "edited"
      ? "done"
      : draft.status === "rejected"
        ? "rejected"
        : "awaiting";

  const steps: TimelineStep[] = [
    {
      id: "email",
      label: "Email Draft",
      detail:
        emailState === "done"
          ? "Approved by you — ready for manual send"
          : emailState === "rejected"
            ? "Rejected — no message will be sent"
            : "Generated by the Strategy Agent, awaiting your review",
      icon: Mail,
      state: emailState,
    },
    {
      id: "best-time",
      label: "Best Time to Send",
      detail: "Send-time optimization — not built yet",
      icon: Clock,
      state: "planned",
    },
    {
      id: "whatsapp",
      label: "WhatsApp Follow-up",
      detail: "No WhatsApp integration in this codebase yet",
      icon: MessageCircle,
      state: "planned",
    },
    {
      id: "twilio",
      label: "Twilio Call",
      detail: "No calling integration in this codebase yet",
      icon: Phone,
      state: "planned",
    },
    {
      id: "crm",
      label: "CRM Update",
      detail: "No CRM read/write integration in this codebase yet",
      icon: Database,
      state: "planned",
    },
    {
      id: "meeting",
      label: "Meeting Scheduling",
      detail: "No calendar integration in this codebase yet",
      icon: CalendarDays,
      state: "planned",
    },
  ];

  return (
    <div className="space-y-0">
      {steps.map((step, i) => {
        const Icon = step.icon;
        const badge = STATE_BADGE[step.state];
        const isLast = i === steps.length - 1;

        return (
          <div key={step.id} className="flex gap-3">
            <div className="flex flex-col items-center">
              <div
                className={cn(
                  "flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border",
                  step.state === "done" && "border-emerald-500/25 bg-emerald-500/10 text-emerald-400",
                  step.state === "awaiting" && "border-amber-500/25 bg-amber-500/10 text-amber-400",
                  step.state === "rejected" && "border-red-500/25 bg-red-500/10 text-red-400",
                  step.state === "planned" && "border-white/8 bg-white/[0.02] text-white/25",
                )}
              >
                {step.state === "done" ? <Check className="h-3.5 w-3.5" /> : step.state === "rejected" ? <X className="h-3.5 w-3.5" /> : <Icon className="h-3.5 w-3.5" />}
              </div>
              {!isLast && <div className="my-0.5 h-6 w-px bg-white/8" />}
            </div>

            <div className={cn("flex-1 pb-5", isLast && "pb-0")}>
              <div className="flex items-center justify-between gap-2">
                <p className={cn("text-[13px] font-medium", step.state === "planned" ? "text-white/40" : "text-white/85")}>
                  {step.label}
                </p>
                <Badge variant={badge.variant}>{badge.label}</Badge>
              </div>
              <p className="mt-0.5 text-[11px] leading-relaxed text-white/35">{step.detail}</p>
            </div>
          </div>
        );
      })}
    </div>
  );
}
